name: push-event

on:
  push:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Init the github-actions repo
        uses: aerius/github-actions/init@v1.1

      - uses: ./aerius-github-actions/events/push-event-action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          ROOT_POM_DIRECTORY: repo/source
