name: pull_request-opened-synchronize-reopened

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Init the github-actions repo
        uses: aerius/github-actions/init@v1.1

      - uses: ./aerius-github-actions/events/pull_request-event-action
        with:
          ROOT_POM_DIRECTORY: repo/source
