name: push-event

on:
  push:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github-actions repo
        uses: actions/checkout@v2
        with:
          repository: aerius/github-actions
          path: aerius-github-actions
          ref: v1.0.2

      - uses: aerius/github-actions/events/push-event-action@v1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          ROOT_POM_DIRECTORY: repo/source
