name: Publish artifact

on:
  push:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --no-transfer-progress -P publish -f source/pom.xml package
      - name: Get Maven project version
        id: get_maven_project_version
        run: |
          VERSION=$(mvn -Dexpression=project.version -q -DforceStdout -f source/pom.xml help:evaluate 2>/dev/null)
          echo "::set-output name=version::${VERSION}"
      # Artifacts should only be published if a release is made, otherwise only on pushes with a SNAPSHOT version
      - if: github.event_name == 'release' || endsWith(steps.get_maven_project_version.outputs.version, '-SNAPSHOT')
        name: Publish Maven Artifacts
        uses: samuelmeuli/action-maven-publish@v1
        with:
          server_id: aerius-nexus
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          maven_args: -DskipTests --no-transfer-progress -P publish -f source/pom.xml
